#!/bin/sh

# Copyright © 2009 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

. common.sh

if [ $# -ne 1 ]
then
    printf 'Usage: %s <input-image>\n' "$0" >&2
    exit 1
fi

in="$1"
eval_image_size "$1"
cat <<EOF
\\input common
\\pdfpagewidth ${width}pt
\\pdfpageheight ${height}pt
\\pdfximage{$in}
\\pdfrefximage\\pdflastximage
\\end
EOF

# vim:ts=4 sw=4 et
