XSL = http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
XMLLINT = xmllint --valid --noout --nonet
XSLTPROC = xsltproc --nonet --param man.charmap.use.subset 0

%.1: %.xml
	$(XMLLINT) $(<)
	$(XSLTPROC) $(XSL) $(<)
	$(srcdir)/tools/encode-manual-page $(@)

# vim:ts=4
