#!/bin/sh

# Copyright © 2015 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdfdjvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

pkgs_base='
build-essential
djvulibre-bin
libdjvulibre-dev
libgraphicsmagick++-dev
libpoppler-dev
libxslt1-dev
pkg-config
'
pkgs_tests='
python-nose
'
pkgs="$pkgs_base"

usage()
{
    printf '%s [--tests]\n' "$0"
}

args=$(getopt -n "$0" -o 'h' --long 'help,tests' -- "$@")
if [ $? -ne 0 ]
then
    usage >&2
    exit 1
fi
eval set -- "$args"
while true
do
    case "$1" in
        -h|--help) usage; exit 0;;
        --tests) pkgs="$pkgs $pkgs_tests"; shift;;
        --) shift; break;;
        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
    esac
done

set -e -x
apt-get install $pkgs
if ! dpkg -L libpoppler-dev | grep -q -E '/GfxState[.]h$'
then
    apt-get install libpoppler-private-dev
fi

# vim:ts=4 sts=4 sw=4 et
