#!/bin/sh
set -e -u
set -x
[ -e configure.ac ]
for file in install-sh config.sub config.guess
do
    rm -f tools/$file
    cp /usr/share/libtool/config/$file tools/
done
rm -f tools/config.rpath
cp /usr/share/gettext/config.rpath tools/
mkdir -p m4
${ACLOCAL:-aclocal} -I m4 --install
${AUTOCONF:-autoconf}
${AUTOHEADER:-autoheader}

# vim:ts=4 sts=4 sw=4 et
