#!/bin/sh
set -e -u
stat configure.ac > /dev/null
PS4='$ '
set -x
for lt_dir in /usr/local/share/libtool /usr/share/libtool
do
    for subdir in config build-aux
    do
        build_aux="$lt_dir/$subdir"
        [ -d "$build_aux" ] && break 2
    done
done
for file in install-sh config.sub config.guess
do
    rm -f tools/$file
    cp "$build_aux/$file" tools/
done
rm -f tools/config.rpath
for gettext_dir in /usr/local/share/gettext /usr/share/gettext
do
    [ -d "$gettext_dir" ] && break
done
cp "$gettext_dir/config.rpath" tools/
mkdir -p m4
${ACLOCAL:-aclocal} -I m4 --install
${AUTOCONF:-autoconf}
${AUTOHEADER:-autoheader}

# vim:ts=4 sts=4 sw=4 et
