#!/bin/sh

# Copyright © 2009-2015 Jakub Wilk <jwilk@jwilk.net>
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

if [ $# -ge 2 ]
then
    printf '%s [revision]\n' "$0" >&2
    exit 1
fi
if ! [ -d .hg ]
then
    printf '%s requires hg checkout\n' "$0" >&2
    exit 1
fi

set -e

pwd="$PWD"
revision="${1:-tip}"
date=$(hg log -r "$revision" --template='{date|isodate}' | head -c 10 | tr -d -)
version=$(hg cat -r "$revision" doc/changelog | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(hg cat -r "$revision" doc/changelog | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Revision: %s\nVersion: %s\n' "$revision" "$version" >&2

set -x
buildroot=$(mktemp -dt pdf2djvu-source-XXXXXXXX)
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export XZ_OPT='-6e'

cd "$buildroot"

# Mercurial archive:
hg archive -r "$revision" -R "$pwd" "pdf2djvu-$version"

# Remove files that only useful in a VCS checkout:
rm -f "pdf2djvu-$version"/.hg*
rm -f "pdf2djvu-$version"/.travis.yml

# Autoconf & company:
cd "pdf2djvu-$version"
private/autogen
rm -Rf *.cache
cd ..

# Generate Makefile.common:
sed -n -e '/^AC_INIT(\[\([^]]*\)\], *\[\([^]]*\)\], *\[\([^]]*\)\],.*/ { s//PACKAGE_NAME=\1\nPACKAGE_VERSION=\2\nPACKAGE_BUGREPORT=\3/p; q }' \
    "pdf2djvu-$version/configure.ac" \
    > "pdf2djvu-$version/Makefile.common"
grep -E 'MSGFMT|MSGMERGE|XGETTEXT' "pdf2djvu-$version/Makefile.common.in" \
| sed >> "pdf2djvu-$version/Makefile.common" \
    -e 's/@MSGFMT@/msgfmt/' \
    -e 's/@MSGMERGE@/msgmerge/' \
    -e 's/@XGETTEXT@/xgettext/'
cat "pdf2djvu-$version/Makefile.common"

# Build the manual page and translations:
make -C "pdf2djvu-$version/po/" all check
make -C "pdf2djvu-$version/doc/"
make -C "pdf2djvu-$version/doc/po/" all check pdf2djvu.pot

# Prepare tests:
make -C "pdf2djvu-$version/tests/" prepare

# Sweep Makefile.common:
rm "pdf2djvu-$version/Makefile.common"

# Tarball with raw source:
tar -caf "$pwd/pdf2djvu-$version.tar.xz" "pdf2djvu-$version"

# Cleanup:
rm -Rf "$buildroot"

# vim:ts=4 sts=4 sw=4 et
