#!/bin/sh

# Copyright © 2009-2015 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdfdjvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

usage()
{
    printf '%s [--print-name] [--no-po-check] [revision]\n' "$0"
}

args=$(getopt -n "$0" -o 'h' --long 'help,no-po-check,print-name' -- "$@")
if [ $? -ne 0 ]
then
    usage >&2
    exit 1
fi
eval set -- "$args"

opt_po_check=y
opt_print_name=
while true
do
    case "$1" in
        -h|--help) usage; exit 0;;
        --no-po-check) opt_po_check=; shift;;
        --print-name) opt_print_name=y; shift;;
        --) shift; break;;
        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
    esac
done

if [ $# -ge 2 ]
then
    usage >&2
    exit 1
fi

set -e -u

hgrepo="$(dirname "$0")/.."
if ! [ -d "$hgrepo/.hg" ]
then
    printf '%s requires hg checkout\n' "$0" >&2
    exit 1
fi
pwd="$PWD"
revision=${1:-.}
read name version release urgency <<EOF
$(hg --cwd "$hgrepo" cat -r "$revision" doc/changelog | head -n1)
EOF
version=${version#(}
version=${version%)}
if [ "$release" = 'UNRELEASED;' ]
then
    date=$(hg --cwd "$hgrepo" log -r "$revision" --template='{date|isodate}' | head -c 10 | tr -d -)
    version="${version}rc${date}"
fi
if [ -n "$opt_print_name" ]
then
    printf '%s\n' "$name-$version.tar.xz"
    exit 0
fi
printf 'Revision: %s\nVersion: %s\n' "$revision" "$version" >&2

set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
tar_opts='--owner root --group root --mode a+rX --format ustar'
xz_opts='-4e'

# Mercurial archive:
hg --cwd "$hgrepo" archive -r "$revision" "$sourceroot/$name-$version"
cd "$sourceroot"/*

# Remove files that only useful in a VCS checkout:
rm .hg*
rm .travis.yml
rm private/build-source-tarball

# Autoconf & company:
private/autogen
rm -r *.cache

# Generate basic autoconf.mk:
sed -n -e '/^AC_INIT(\[\([^]]*\)\], *\[\([^]]*\)\], *\[\([^]]*\)\],.*/ { s//PACKAGE_NAME=\1\nPACKAGE_VERSION=\2\nPACKAGE_BUGREPORT=\3/p; q }' \
    "configure.ac" \
    > autoconf.mk
grep -E 'MSGFMT|MSGMERGE|XGETTEXT' autoconf.mk.in \
| sed >> autoconf.mk \
    -e 's/@MSGFMT@/msgfmt/' \
    -e 's/@MSGMERGE@/msgmerge/' \
    -e 's/@XGETTEXT@/xgettext/'
cat autoconf.mk

# Build the manual page and translations:
make -C po/ all
[ -z "$opt_po_check" ] || make -C po/ check
make -C doc/
make -C doc/po/ all pdf2djvu.pot
[ -z "$opt_po_check" ] || make -C doc/po/ check
# Prepare tests:
make -C tests/ prepare

# Sweep autoconf.mk:
rm autoconf.mk

# Tarball with raw source:
cd ..
tar $tar_opts -I "xz $xz_opts" -cf "$pwd/$name-$version.tar.xz" */

# Cleanup:
rm -r "$sourceroot"
set +x
cd "$pwd"
ls -d "$name-$version.tar.xz"

# vim:ts=4 sts=4 sw=4 et
