#!/bin/sh

# Copyright © 2016-2022 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdf2djvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

here=${0%/*}
here=${here#./}
root="$here/../"
root=${root#private/../}
rst2xml=$(command -v rst2xml) \
|| rst2xml=$(command -v rst2xml.py) \
|| { printf 'rst2xml not found\n' >&2; exit 1; }
rst2xml=${rst2xml##*/}
options='--input-encoding=UTF-8 --strict'
if [ $# -eq 0 ]
then
    grep -r -w -l 'ft[=]rst' "${root:-.}"
else
    printf '%s\n' "$@"
fi |
xargs -t -I{} "$rst2xml" $options {} /dev/null

# vim:ts=4 sts=4 sw=4 et
