#!/bin/sh
set -e -u
set -x
for file in install-sh config.sub config.guess
do
  rm -f tools/$file
  cp $(ls -d /usr/share/automake*/$file | head -n1) tools/
done
rm -f tools/config.rpath
cp /usr/share/gettext/config.rpath tools/
${ACLOCAL:-aclocal} -I m4 --install
${AUTOCONF:-autoconf}
${AUTOHEADER:-autoheader}
