#!/bin/sh

# Copyright © 2009, 2010, 2011 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

if [ $# -ne 1 ]
then
    printf '%s <tarball>\n' "$0"
    exit 1
fi

set -e
set -x

export ZIPOPT='-9Xr'

cwd=$(pwd)
tarball=$(readlink -f "$1")
tarball_base="${tarball%.tar.*}"
root=$(mktemp -dt pdf2djvu-win32-XXXXXX)
version="${tarball_base##*_}"

mkdir -pv "$root/src/"
cd "$root/src/"
tar -xvvf "$tarball"
mv -v pdf2djvu-* pdf2djvu
cd "$root"
ls -lR src/
cp -rv src/pdf2djvu/win32/* .

# Build source:

stamps=$(grep -o '^[^ ]*source-stamp' Makefile | sort -u)
make $stamps
tag="pdf2djvu-win32-source_$version"
cp -rl src "$tag"
find "$tag" -name source-stamp -delete
zip "$cwd/$tag.zip" "$tag"
mv "$tag" src

# Build binaries:

make all
tag="pdf2djvu-win32_$version"
mv dist "$tag"
zip "$cwd/$tag.zip" "$tag"

# Cleanup:

cd /
rm -rf "$root"

# vim:ts=4 sw=4 et
