#!/usr/bin/perl -pi

# Copyright © 2014 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

use strict;
use warnings;

# Work-around for DocBook XSL capitalization bug:
# https://bugs.debian.org/758262#20

if (/^[.]SH /) {
    s/(\\[(][,~'][a-z])/\U$1/g;
}

# vim:ts=4 sw=4 et
