#!/usr/bin/perl -pi

# Copyright © 2014 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

use strict;
use warnings;

# Work-arounds for DocBook XSL capitalization bugs

if (/^[.]SH /) {
    s/(\\[(][,~'][a-z])/\U$1/g; # https://bugs.debian.org/758262#20
    s/\\[(]ss/SS/g; # https://bugs.debian.org/773444
}

# vim:ts=4 sts=4 sw=4 et
