#!/usr/bin/perl -pi

# Copyright © 2014 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdf2djvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

use strict;
use warnings;

# Work-arounds for DocBook XSL capitalization bugs

if (/^[.]SH /) {
    s/(\\[(][,~'][a-z])/\U$1/g; # https://bugs.debian.org/758262#20
    s/\\[(]ss/SS/g; # https://bugs.debian.org/773444
}

# vim:ts=4 sts=4 sw=4 et
