#!/bin/sh
pdf2djvu_version=`sed -n -e '1 s/.*(\([0-9.]*\)).*/\1/p' < debian/changelog`
poppler_info="poppler `pkg-config --modversion poppler-splash`" || exit 1
djvulibre_info="DjVuLibre `pkg-config --modversion ddjvuapi`" || exit 1
info="$djvulibre_info, $poppler_info"
printf 'static const char PDF2DJVU_VERSION[] = "pdf2djvu %s (%s)";\n' "$pdf2djvu_version" "$info" 
