#!/bin/sh

# Copyright © 2015-2022 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdf2djvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

usage()
{
    printf '%s LOCALE-DIR MO-FILE...\n' "$0"
}

set -e -u
: "${INSTALL:=install}"
[ $# -ge 1 ] || { usage >&2; exit 1; }
localedir="$1"
shift
for mofile in "$@"
do
    basename=${mofile##*/}
    locale=${basename%.*}
    (
        PS4='$ '
        set -x
        $INSTALL -d "$localedir/$locale/LC_MESSAGES"
        $INSTALL -m 644 "$mofile" "$localedir/$locale/LC_MESSAGES/pdf2djvu.mo"
    )
done

# vim:ts=4 sts=4 sw=4 et
