#!/bin/sh

# Copyright © 2015 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdf2djvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

usage()
{
    printf '%s <mandir> <manpage>...\n' "$0"
}

set -e -u
: "${INSTALL:=install}"
[ $# -ge 1 ] || { usage; exit 1; }
mandir="$1"
shift
for manpage in "$@"
do
    basename=$(basename "$manpage")
    suffix=${basename#*.}
    locale=${suffix%.*}
    [ "$locale" = "$suffix" ] && locale=
    section=${suffix#*.}
    basename=${basename%%.*}
    (
        PS4='$ '
        set -x
        $INSTALL -d "$mandir/$locale/man$section"
        $INSTALL -m 644 "$manpage" "$mandir/$locale/man$section/$basename.$section"
    )
done

# vim:ts=4 sts=4 sw=4 et
