#!/bin/sh

# Copyright © 2007-2018 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of pdf2djvu.
#
# pdf2djvu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# pdf2djvu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

if [ $# -ne 1 ]
then
  printf 'Usage: %s <poppler-source-directory>\n' "$0" >&2
  exit 1
fi
source_dir=$1
include_dir=$(pkg-config --cflags-only-I poppler-splash | sed -n -e '/^-I/ { s/^-I//; s/ .*//; p; q;}')
if [ -z "$include_dir" ]
then
  printf 'Unable to determine destination directory\n' >&2
  exit 1
fi
cat <<EOF >&2
I will copy header files from $source_dir into $include_dir
Press enter to continue
EOF
read
mkdir -p "$include_dir/goo"
mkdir -p "$include_dir/splash"
cp "$source_dir/poppler/"*.h "$include_dir"
cp "$source_dir/goo/"*.h "$include_dir/goo"
cp "$source_dir/splash/"*.h "$include_dir/splash"
