#!/bin/sh

# Copyright © 2009, 2013 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

exec sed -e '
/<!--# *\(.*\) *#-->/ {
  s//\1/
  b
}
/<!--.*-->/ {
  s///g
  b
}
s/\\\\/\\\\/g
s/"/\\"/g
s/^/"/
s/$/\\n"/
'

# vim:ts=2 sts=2 sw=2 et
