#!/bin/sh

# Copyright © 2009 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

exec sed \
  -e '/<!--# *\(.*\) *#-->/ { s//\1/; b; }' \
  -e '/<!--.*-->/ { s///g; b; }' \
  -e 's/\\\\/\\\\/g' \
  -e 's/"/\\"/g' \
  -e 's/^/"/; s/$/\\n"/'

# vim:ts=2 sw=2 et
